#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

DISTRO_NAME=openshift-origin-client-tools-v3.7.0-7ed6862-linux-64bit

# unpack the oc tool
{
    cd /tmp/artifacts
    tar xzf "$DISTRO_NAME.tar.gz"
    mv "$DISTRO_NAME"/oc /usr/src/app/oc
}